#------------------------------------------------------------------------------
# Server Configurations
#
server:
  port: 8081

#------------------------------------------------------------------------------
# MySQL Database config
#
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_contacttracer?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: "/api"

  #------------------------------------------------------------------------------
  # OAuth2 Authorization Servers
  #
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fb809632e360f0b89c95
            client-secret: b008940f86bf6c947b0c26b340c71fcb33929530

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace